
import styles from './page.module.css';

import { Analytics } from '@vercel/analytics/react';
import { SpeedInsights } from '@vercel/speed-insights/next';
 
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      

      <body className={styles.body1}>{children}</body>
      <Analytics />
      <SpeedInsights />
    </html>
  )
}
